logLevel: 4
hotspot: true
skip: true
report: true
cert: config/hijack.crt
key: config/hijack.key
host: 0.0.0.0:8084
headers: config/headers.yml
qrcode: config/qrcode.yml
imageURL: https://img95.699pic.com/xsj/0x/3k/lt.jpg!/fh/300
qrcodeURL: https://www.baidu.com
image: config/hijack.png
html: config/hijack.html
targets: config/target.list
template: config/template.html
captureProxy: 0.0.0.0:48080
captureWifi: 0.0.0.0:58080
fileServerHost: 0.0.0.0:8081